spring: 
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouses
    username: postgres
    password: Bearpaw11
  output:
        ansi:
            enabled: ALWAYS
  #jpa:

  #  generate-ddl: true
  #  hibernate:
  #      ddl-auto: create
  #  properties:
  #      hibernate:
  #          dialect: org.hibernate.dialect.PostgreSQLDialect  